services:
  infra:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: infra
    image: databot-infra
    container_name: prod-databot-infra
    hostname: prod-databot-infra
    environment:
      - TZ=Pacific/Auckland # Your timezone
    working_dir: /databot/infra/
    volumes:
      - ..:/databot/
    command: [ "sleep", infinity ]

  store:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: store
    image: databot-store
    container_name: prod-databot-store
    hostname: prod-databot-store
    restart: always
    env_file:
      - ../store/shell/env/prod.sh
    ports:
      - 5667:5666
    working_dir: /databot/store/
    volumes:
      - ..:/databot/
