services:
  bot:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: bot
    depends_on:
      - store
    image: databot-bot
    container_name: local-databot-bot
    hostname: local-databot-bot
    environment:
      - ENV_NAME=local
      - LOG_LEVEL=trace
    working_dir: /databot/bot/
    volumes:
      - ..:/databot/
    command: [ "sleep", infinity ]

  store:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: timescaledb
    image: databot-store
    container_name: local-databot-store
    hostname: local-databot-store
    restart: always
    environment:
      - POSTGRES_USER=pgroot
      - POSTGRES_PASSWORD=pgroot
    ports:
      - 5667:5666
    working_dir: /databot/store/
    volumes:
      - ..:/databot/
