services:
  bot:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: bot
    depends_on:
      - store
    image: databot-bot
    container_name: local-databot-bot
    hostname: local-databot-bot
    environment:
      - TZ=Pacific/Auckland # Your timezone
    env_file:
      - ../bot/script/env/local.sh
    working_dir: /databot/bot/
    volumes:
      - ..:/databot/
    command: [ "sleep", infinity ]

  store:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: store
    image: databot-store
    container_name: local-databot-store
    hostname: local-databot-store
    restart: always
    env_file:
      - ../store/script/env/local.sh
    ports:
      - 5667:5666
    working_dir: /databot/store/
    volumes:
      - ..:/databot/
