services:
  infra:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: infra
    image: databot-infra
    container_name: prod-databot-infra
    hostname: prod-databot-infra
    working_dir: /databot/infra/
    volumes:
      - ..:/databot/
    command: [ "sleep", infinity ]

  store:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: timescaledb
    image: databot-store
    container_name: prod-databot-store
    hostname: prod-databot-store
    restart: always
    environment:
      - POSTGRES_USER=pgroot
      - POSTGRES_PASSWORD=pgroot # TODO: import from secret
    ports:
      - 5667:5666
    working_dir: /databot/store/
    volumes:
      - ..:/databot/
